server:
  error:
    whitelabel:
      enabled: false
  port: 8090
spring:
  application:
    name: studentdemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
